server:
  port: 8081
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test
    username: root
    password: root
    hikari:
      maximum-pool-size: 20
      minimum-idle: 10
  application:
    name: user-service
mybatis:
  type-aliases-package: com.leyou.pojo

# eureka 配置
eureka:
  client:
    service-url:  #EurekaServer地址
      defaultZone: http://127.0.0.1:10086/eureka,http://127.0.0.1:10087/eureka
    register-with-eureka: true
  instance:
    prefer-ip-address: true # 调用getHostName获取实例的hostname返回ip而不是服务名称
    ip-address: 127.0.0.1 # 配置自己的ip信息,不配置会自己获取
    lease-expiration-duration-in-seconds: 10  # 改服务的失效时间 默认为90s
    lease-renewal-interval-in-seconds: 5   # 服务续约间隔 默认30s
    instance-id: ${spring.application.name}:${server.port}  # 是区分同一服务不同实例的标准,不能重复